[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = false
panic = 'unwind'
rpath = false

[workspace]
members = [
    "oapth",
    "oapth-cli",
    "oapth-macros"
]