version: "3"

services:
    # MariaDB

    mariadb_10:
        environment:
            MYSQL_DATABASE: oapth
            MYSQL_PASSWORD: oapth
            MYSQL_ROOT_PASSWORD: oapth
            MYSQL_USER: oapth
        image: mariadb:10
        ports:
            - 3306:3306

    # Mssql

    mssql_2019:
        build:
            context: .
            dockerfile: mssql/Dockerfile
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: yourStrong(!)Password
        ports:
          - 1433:1433

    # MySQL

    mysql_8:
        environment:
            MYSQL_DATABASE: oapth
            MYSQL_PASSWORD: oapth
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: oapth
            MYSQL_USER: oapth
        image: mysql:8
        ports:
            - 3307:3306

    # PostgreSQL

    postgres_13:
        environment:
            POSTGRES_DB: oapth
            POSTGRES_PASSWORD: oapth
            POSTGRES_USER: oapth
        image: postgres:13
        ports:
            - 5432:5432