[dependencies]
arrayvec = { default-features = false, version = "0.5" }
chrono = { default-features = false, version = "0.4" }
futures = { default-features = false, optional = true, version = "0.3" }
mysql_async = { default-features = false, optional = true, version = "0.25" }
rusqlite = { default-features = false, features = ["chrono", "trace"], optional = true, version = "0.24" }
siphasher = { default-features = false, version = "0.3" }
sqlx-core = { branch = "date", default-features = false, features = ["chrono"], git = "https://github.com/c410-f3r/sqlx", optional = true }
tokio = { default-features = false, features = ["rt-core"], optional = true, version = "0.2" }
tokio-postgres = { default-features = false, features = ["runtime", "with-chrono-0_4"], optional = true, version = "0.5" }

[dev-dependencies]
env_logger = { default-features = false, version = "0.8" }
tokio = { default-features = false, features = ["macros", "rt-core"], version = "0.2" }

[features]
default = []
dev-tools = []
std = []
with-mysql_async = ["mysql_async", "std"]
with-rusqlite = ["rusqlite", "std"]
with-sqlx-mssql = ["futures", "sqlx-core/mssql", "std"]
with-sqlx-mysql = ["futures", "sqlx-core/mysql", "std"]
with-sqlx-postgres = ["futures", "sqlx-core/postgres", "std"]
with-sqlx-runtime-actix = ["sqlx-core/runtime-actix", "std"]
with-sqlx-runtime-async-std = ["sqlx-core/runtime-async-std", "std"]
with-sqlx-runtime-tokio = ["sqlx-core/runtime-tokio", "std"]
with-sqlx-sqlite = ["futures", "sqlx-core/sqlite", "std"]
with-tokio-postgres = ["std", "tokio", "tokio-postgres"]

# Internal "private" feature that is meaningless for public usage
_integration_tests = []

[package]
authors = ["Caio Fernandes <c410.f3r@gmail.com>"]
categories = ["database"]
description = "Oapth"
edition = "2018"
keywords = ["database", "migration", "oapth", "sql"]
license = "Apache-2.0"
name = "oapth"
readme = "README.md"
repository = "https://github.com/c410-f3r/oapth"
version = "0.1.0"
