[dependencies]

# Back ends

diesel = { default-features = false, features = ["chrono"], git = "https://github.com/diesel-rs/diesel", optional = true }
futures = { default-features = false, optional = true, version = "0.3" }
mysql_async = { default-features = false, optional = true, version = "0.25" }
rusqlite = { default-features = false, features = ["chrono", "trace"], optional = true, version = "0.24" }
sqlx-core = { default-features = false, features = ["chrono"], optional = true, version = "0.4" }
tiberius = { default-features = false, optional = true, version = "0.4" }
tokio = { default-features = false, optional = true, version = "0.2" }
tokio-postgres = { default-features = false, features = ["runtime", "with-chrono-0_4"], optional = true, version = "0.5" }

# Internals

arrayvec = { default-features = false, version = "0.5" }
chrono = { default-features = false, version = "0.4" }
oapth-macros = { default-features = false, path = "../oapth-macros" }
siphasher = { default-features = false, version = "0.3" }

[dev-dependencies]
chrono = { default-features = false, features = ["clock"], version = "0.4" }
env_logger = { default-features = false, version = "0.8" }
tokio = { default-features = false, features = ["macros", "net", "rt-core"], version = "0.2" }
tokio-util = { default-features = false, features = ["compat"], version = "0.3" }

[features]
default = ["std"]
dev-tools = []
std = []
with-diesel-mysql = ["diesel/mysql", "std"]
with-diesel-pg = ["diesel/postgres", "std"]
with-diesel-sqlite = ["diesel/sqlite", "std"]
with-mysql_async = ["mysql_async", "std"]
with-rusqlite = ["rusqlite", "std"]
with-sqlx-mssql = ["futures", "sqlx-core/mssql", "std"]
with-sqlx-mysql = ["futures", "sqlx-core/mysql", "std"]
with-sqlx-pg = ["futures", "sqlx-core/postgres", "std"]
with-sqlx-sqlite = ["futures", "sqlx-core/sqlite", "std"]
with-tiberius = ["futures", "std", "tiberius"]
with-tokio-postgres = ["std", "tokio", "tokio-postgres"]

# Internal "private" features that should be meaningless for public usage

_integration-tests = ["std"]
_sqlx_hack = ["sqlx-core/runtime-tokio-rustls"]

[package]
authors = ["Caio Fernandes <c410.f3r@gmail.com>"]
categories = ["database"]
description = "Flexible version control for databases through SQL migrations"
edition = "2018"
keywords = ["database", "migration", "oapth", "sql"]
license = "Apache-2.0"
name = "oapth"
readme = "README.md"
repository = "https://github.com/c410-f3r/oapth"
version = "0.1.0"

[package.metadata.docs.rs]
all-features = true