name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  fuzz:
    name: Fuzz tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2020-09-11

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-fuzz
          use-tool-cache: true

      - run: cargo fuzz run parse_migration -- -max_len=8 -runs=10000
      - run: cargo fuzz run validate -- -runs=10000

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: [
          "integration-tests-mariadb",
          "integration-tests-mysql",
          "integration-tests-postgres",
          "integration-tests-sqlite"
        ]
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - run: docker-compose -f oapth-test-utils/docker-compose.yml up -d

      - run: sleep 60

      - run: ./scripts/${{ matrix.scripts }}.sh

  internal:
    name: Internal tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          profile: minimal
          toolchain: stable

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - run: ./scripts/internal-tests.sh