name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  fuzz:
    name: Fuzz tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2023-10-15

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-fuzz
          use-tool-cache: true

      - run: ./.scripts/fuzz.sh

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: [
          "integration-tests-mssql",
          "integration-tests-mysql",
          "integration-tests-postgres",
          "integration-tests-sqlite"
        ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2023-10-15

      - uses: Swatinem/rust-cache@v2

      - run: docker-compose -f .test-utils/docker-compose.yml up -d

      - run: sleep 60

      - run: ./.scripts/${{ matrix.scripts }}.sh

  internal:
    name: Internal tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scripts: [
          "internal-tests-oapth-0",
          "internal-tests-oapth-1",
        ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          profile: minimal
          toolchain: nightly-2023-10-15

      - uses: Swatinem/rust-cache@v2

      - run: ./.scripts/${{ matrix.scripts }}.sh
